package com.arc_e_tect.gradle.apionly.subscriber;

import java.io.File;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

/**
 * apionly.lock -- what this project is actually building against.
 *
 * Committed, and recording per target the resolved version, the channel it came
 * from, and the SHA-256 of every fetched file. That is the verbatim guarantee:
 * `verifyApiSpec` re-hashes and fails when anything drifted, whether because a
 * generated file was hand-edited or because a tag was moved under the build's
 * feet. Run it in CI and contract drift becomes a build failure rather than a
 * production surprise.
 *
 * The format is deliberately a small, sorted, line-oriented text file rather
 * than JSON: it is read by people in review far more often than by machines, and
 * a one-line diff should mean one thing changed.
 */
public final class Lockfile {

    /** The format this class reads and writes. Bumped only when the format changes. */
    public static final int FORMAT_VERSION = 1;

    /**
     * What is locked for one target.
     *
     * @param target  the contract the entry is for
     * @param version the version resolved when it was fetched
     * @param channel the channel it was fetched from
     * @param files   each document's filename mapped to its SHA-256
     */
    public record Entry(String target, String version, String channel, Map<String, String> files) {}

    private final Map<String, Entry> entries = new TreeMap<>();

    /** Creates an empty lockfile. */
    public Lockfile() {
        // Entries are added through put(Entry), or read from disk by read(File).
    }

    /**
     * Reads a lockfile, or returns an empty one if it does not exist.
     *
     * <p>A missing file is an ordinary first-run state, not an error: a project
     * that has never fetched anything has nothing locked yet.</p>
     *
     * @param file the lockfile to read
     * @return the parsed lockfile, empty if the file is absent
     * @throws java.io.UncheckedIOException if the file exists but cannot be read
     */
    public static Lockfile read(File file) {
        Lockfile lock = new Lockfile();
        if (!file.exists()) {
            return lock;
        }
        List<String> lines;
        try {
            lines = Files.readAllLines(file.toPath(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException("cannot read " + file, e);
        }

        String target = null;
        String version = null;
        String channel = null;
        Map<String, String> files = new LinkedHashMap<>();

        for (String raw : lines) {
            String line = raw.strip();
            if (line.isEmpty() || line.startsWith("#")) {
                continue;
            }
            if (line.startsWith("target ")) {
                if (target != null) {
                    lock.entries.put(target, new Entry(target, version, channel, files));
                }
                target = line.substring("target ".length()).strip();
                version = null;
                channel = null;
                files = new LinkedHashMap<>();
            } else if (line.startsWith("version ")) {
                version = line.substring("version ".length()).strip();
            } else if (line.startsWith("channel ")) {
                channel = line.substring("channel ".length()).strip();
            } else if (line.startsWith("sha256 ")) {
                String[] parts = line.substring("sha256 ".length()).strip().split("\\s+", 2);
                if (parts.length == 2) {
                    files.put(parts[1], parts[0]);
                }
            }
        }
        if (target != null) {
            lock.entries.put(target, new Entry(target, version, channel, files));
        }
        return lock;
    }

    /**
     * Writes the lockfile, with targets and their files in sorted order.
     *
     * <p>The ordering matters: this file is read in review far more often than by
     * a machine, and a one-line diff should mean one thing changed rather than a
     * reordering.</p>
     *
     * @param file where to write
     * @throws java.io.UncheckedIOException if it cannot be written
     */
    public void write(File file) {
        StringBuilder out = new StringBuilder();
        out.append("# apionly.lock -- the published contracts this project builds against.\n");
        out.append("# Generated by the Arc-E-Tect API-Only Subscriber. Commit it; do not edit it.\n");
        out.append("# Run `verifyApiSpec` to check that what is on disk still matches.\n");
        out.append("format ").append(FORMAT_VERSION).append('\n');

        for (Entry entry : entries.values()) {
            out.append('\n');
            out.append("target ").append(entry.target()).append('\n');
            out.append("version ").append(entry.version()).append('\n');
            out.append("channel ").append(entry.channel()).append('\n');
            new TreeMap<>(entry.files()).forEach(
                (name, sha) -> out.append("sha256 ").append(sha).append(' ').append(name).append('\n'));
        }

        try {
            File parent = file.getParentFile();
            if (parent != null) {
                Files.createDirectories(parent.toPath());
            }
            Files.writeString(file.toPath(), out.toString(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException("cannot write " + file, e);
        }
    }

    /**
     * The entry for one target.
     *
     * @param target the contract to look up
     * @return its entry, or {@code null} if nothing is locked for it
     */
    public Entry get(String target) {
        return entries.get(target);
    }

    /**
     * Adds or replaces the entry for a target.
     *
     * @param entry what to record
     */
    public void put(Entry entry) {
        entries.put(entry.target(), entry);
    }

    /**
     * Every target with an entry, in sorted order.
     *
     * @return the locked target names
     */
    public List<String> targets() {
        return new ArrayList<>(entries.keySet());
    }

    /**
     * The SHA-256 of a file, lowercase hexadecimal.
     *
     * @param file the file to hash
     * @return its digest as 64 hexadecimal characters
     * @throws java.io.UncheckedIOException if the file cannot be read
     */
    public static String sha256(File file) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(Files.readAllBytes(file.toPath()));
            StringBuilder hex = new StringBuilder(hash.length * 2);
            for (byte b : hash) {
                hex.append(Character.forDigit((b >> 4) & 0xF, 16));
                hex.append(Character.forDigit(b & 0xF, 16));
            }
            return hex.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 is not available", e);
        } catch (IOException e) {
            throw new UncheckedIOException("cannot hash " + file, e);
        }
    }
}
