package com.arc_e_tect.gradle.apionly.subscriber;

import java.io.File;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

/**
 * apionly.lock -- what this project is actually building against.
 *
 * Committed, and recording per target the resolved version, the channel it came
 * from, and the SHA-256 of every fetched file. That is the verbatim guarantee:
 * `verifyApiSpec` re-hashes and fails when anything drifted, whether because a
 * generated file was hand-edited or because a tag was moved under the build's
 * feet. Run it in CI and contract drift becomes a build failure rather than a
 * production surprise.
 *
 * The format is deliberately a small, sorted, line-oriented text file rather
 * than JSON: it is read by people in review far more often than by machines, and
 * a one-line diff should mean one thing changed.
 */
public final class Lockfile {

    /** Bumped only when the file format itself changes. */
    public static final int FORMAT_VERSION = 1;

    public record Entry(String target, String version, String channel, Map<String, String> files) {}

    private final Map<String, Entry> entries = new TreeMap<>();

    public static Lockfile read(File file) {
        Lockfile lock = new Lockfile();
        if (!file.exists()) {
            return lock;
        }
        List<String> lines;
        try {
            lines = Files.readAllLines(file.toPath(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException("cannot read " + file, e);
        }

        String target = null;
        String version = null;
        String channel = null;
        Map<String, String> files = new LinkedHashMap<>();

        for (String raw : lines) {
            String line = raw.strip();
            if (line.isEmpty() || line.startsWith("#")) {
                continue;
            }
            if (line.startsWith("target ")) {
                if (target != null) {
                    lock.entries.put(target, new Entry(target, version, channel, files));
                }
                target = line.substring("target ".length()).strip();
                version = null;
                channel = null;
                files = new LinkedHashMap<>();
            } else if (line.startsWith("version ")) {
                version = line.substring("version ".length()).strip();
            } else if (line.startsWith("channel ")) {
                channel = line.substring("channel ".length()).strip();
            } else if (line.startsWith("sha256 ")) {
                String[] parts = line.substring("sha256 ".length()).strip().split("\\s+", 2);
                if (parts.length == 2) {
                    files.put(parts[1], parts[0]);
                }
            }
        }
        if (target != null) {
            lock.entries.put(target, new Entry(target, version, channel, files));
        }
        return lock;
    }

    public void write(File file) {
        StringBuilder out = new StringBuilder();
        out.append("# apionly.lock -- the published contracts this project builds against.\n");
        out.append("# Generated by the Arc-E-Tect API-Only Subscriber. Commit it; do not edit it.\n");
        out.append("# Run `verifyApiSpec` to check that what is on disk still matches.\n");
        out.append("format ").append(FORMAT_VERSION).append('\n');

        for (Entry entry : entries.values()) {
            out.append('\n');
            out.append("target ").append(entry.target()).append('\n');
            out.append("version ").append(entry.version()).append('\n');
            out.append("channel ").append(entry.channel()).append('\n');
            new TreeMap<>(entry.files()).forEach(
                (name, sha) -> out.append("sha256 ").append(sha).append(' ').append(name).append('\n'));
        }

        try {
            File parent = file.getParentFile();
            if (parent != null) {
                Files.createDirectories(parent.toPath());
            }
            Files.writeString(file.toPath(), out.toString(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException("cannot write " + file, e);
        }
    }

    public Entry get(String target) {
        return entries.get(target);
    }

    public void put(Entry entry) {
        entries.put(entry.target(), entry);
    }

    public List<String> targets() {
        return new ArrayList<>(entries.keySet());
    }

    public static String sha256(File file) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hash = digest.digest(Files.readAllBytes(file.toPath()));
            StringBuilder hex = new StringBuilder(hash.length * 2);
            for (byte b : hash) {
                hex.append(Character.forDigit((b >> 4) & 0xF, 16));
                hex.append(Character.forDigit(b & 0xF, 16));
            }
            return hex.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("SHA-256 is not available", e);
        } catch (IOException e) {
            throw new UncheckedIOException("cannot hash " + file, e);
        }
    }
}
