"use strict";

// Generated aggregate bundles.
//
// A portfolio view of the OpenAPI surface is just another bundle root: every
// path body already lives in a $ref'd fragment, so a whole-landscape table of
// contents costs one hand-written file that duplicates no contract text.
//
// AsyncAPI cannot be written that way. Its operations use document-root pointers
// -- `channel: {$ref: '#/channels/auditV1'}` -- and `#` resolves against whatever
// file contains it, so moving an operation into a fragment breaks it. A
// hand-written async portfolio would therefore have to copy every operation
// verbatim, and that copy would start rotting the moment a member changed.
//
// So it is generated instead: the aggregate's bundle root is synthesised into the
// staged tree from its members, immediately before bundling. Nothing is
// duplicated in the source, and the view cannot fall behind its members.

const fs = require("fs");
const path = require("path");
const YAML = require("yaml");

class AggregateError extends Error {}

function mergeSection(into, from, section, member, seen) {
    if (!from[section]) return;
    for (const [key, value] of Object.entries(from[section])) {
        if (seen[section] && seen[section][key]) {
            throw new AggregateError(
                `aggregate: '${member}' redefines ${section}.${key}, already contributed by ` +
                `'${seen[section][key]}'. Rename it, or leave it out of the aggregate.`
            );
        }
        into[section] = into[section] || {};
        into[section][key] = value;
        seen[section] = seen[section] || {};
        seen[section][key] = member;
    }
}

/**
 * Synthesise an aggregate AsyncAPI bundle root into the staged tree.
 *
 * @returns {string} the path of the generated bundle root
 */
function generateAsyncApi(config, target, { log = () => {} } = {}) {
    const spec = config.targets[target].asyncapi;
    const members = spec.aggregate;
    if (!Array.isArray(members) || members.length === 0) {
        throw new AggregateError(`target '${target}': asyncapi.aggregate must list at least one target`);
    }

    const merged = { asyncapi: null, info: null, servers: {}, channels: {}, operations: {} };
    const seen = {};

    for (const member of members) {
        if (!config.targets[member] || !config.targets[member].asyncapi) {
            throw new AggregateError(
                `target '${target}': aggregate member '${member}' declares no asyncapi bundle`
            );
        }
        const file = path.join(config.stagingDir("asyncapi"), config.targets[member].asyncapi.bundle);
        if (!fs.existsSync(file)) {
            throw new AggregateError(`aggregate member '${member}': bundle root not found at ${file}`);
        }
        const doc = YAML.parse(fs.readFileSync(file, "utf8"));

        merged.asyncapi = merged.asyncapi || doc.asyncapi;
        mergeSection(merged, doc, "servers", member, seen);
        mergeSection(merged, doc, "channels", member, seen);
        mergeSection(merged, doc, "operations", member, seen);
    }

    // The aggregate's own identity, not any member's.
    merged.info = spec.info || {
        title: `${target} (aggregate)`,
        version: "0.0.0",
        description: `Every event contract published across ${members.join(", ")}.`,
    };

    const out = path.join(config.stagingDir("asyncapi"), spec.bundle);
    fs.mkdirSync(path.dirname(out), { recursive: true });
    fs.writeFileSync(
        out,
        `# GENERATED by api-only-publisher from: ${members.join(", ")}\n` +
        `# Do not edit, and do not commit: it is rebuilt into the staging tree on every build.\n` +
        YAML.stringify(merged)
    );
    log(`-- Generated aggregate ${path.basename(out)} from ${members.join(", ")}`);
    return out;
}

function isAggregate(config, target, kind) {
    const spec = config.targets[target][kind];
    return Boolean(spec && spec.aggregate);
}

module.exports = { generateAsyncApi, isAggregate, AggregateError };
