package com.arc_e_tect.gradle.apionly.transcriberj;

import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.tasks.CacheableTask;
import org.gradle.api.tasks.OutputDirectory;
import org.gradle.api.tasks.OutputFile;
import org.gradle.api.tasks.TaskAction;
import org.gradle.workers.WorkQueue;
import org.gradle.workers.WorkerExecutor;

import javax.inject.Inject;

/**
 * Generates the core of one contract's class tree: the schema classes, the operations and the
 * invalid-request cases, and the endpoint index. Each emitter's output is generated by a task
 * of its own, {@link GenerateEmitterSourcesTask}, so that changing one emitter regenerates only
 * that emitter.
 *
 * <p>It writes its part of the report as fragments, which {@link ReportContractSourcesTask}
 * merges with the emitters' into the one report of the subscription.
 */
@CacheableTask
public abstract class GenerateContractSourcesTask extends ContractSourcesTask {

    /** Creates the task. */
    public GenerateContractSourcesTask() {
    }

    /**
     * Where the core's sources go.
     *
     * @return the directory
     */
    @OutputDirectory
    public abstract DirectoryProperty getOutputDirectory();

    /**
     * Where the core's resources go.
     *
     * @return the directory
     */
    @OutputDirectory
    public abstract DirectoryProperty getResourceDirectory();

    /**
     * Where the endpoint index goes.
     *
     * @return the index
     */
    @OutputFile
    public abstract RegularFileProperty getEndpointIndex();

    /**
     * Where the core's part of the report goes, as JSON.
     *
     * @return the fragment
     */
    @OutputFile
    public abstract RegularFileProperty getReportFragment();

    /**
     * Where the core's part of the report goes, as AsciiDoc.
     *
     * @return the fragment
     */
    @OutputFile
    public abstract RegularFileProperty getAsciiDocFragment();

    /**
     * Where the machine-readable report of every generated valid value goes; nothing is written
     * when it is not set.
     *
     * @return the report
     */
    @OutputFile
    @org.gradle.api.tasks.Optional
    public abstract RegularFileProperty getValidValuesReport();

    /**
     * Gradle's worker executor.
     *
     * @return the executor
     */
    @Inject
    protected abstract WorkerExecutor getWorkerExecutor();

    /** Generates the core. */
    @TaskAction
    public void generate() {
        LockedContract locked = locked();
        WorkQueue queue = getWorkerExecutor().noIsolation();
        queue.submit(GenerateContractSourcesAction.class, parameters -> {
            fill(parameters, locked);
            parameters.getOutputDirectory().set(getOutputDirectory());
            parameters.getResourceDirectory().set(getResourceDirectory());
            parameters.getEndpointIndex().set(getEndpointIndex());
            parameters.getReportFragment().set(getReportFragment());
            parameters.getAsciiDocFragment().set(getAsciiDocFragment());
            parameters.getValidValuesReport().set(getValidValuesReport());
        });
        queue.await();
    }
}
