package com.arc_e_tect.gradle.apionly.transcriberj.core;

import com.arc_e_tect.gradle.apionly.transcriberj.model.CanonicalJson;
import com.arc_e_tect.gradle.apionly.transcriberj.model.Const;
import com.arc_e_tect.gradle.apionly.transcriberj.model.Constraints;
import com.arc_e_tect.gradle.apionly.transcriberj.model.Construct;
import com.arc_e_tect.gradle.apionly.transcriberj.model.ContractModel;
import com.arc_e_tect.gradle.apionly.transcriberj.model.MediaType;
import com.arc_e_tect.gradle.apionly.transcriberj.model.Operation;
import com.arc_e_tect.gradle.apionly.transcriberj.model.Parameter;
import com.arc_e_tect.gradle.apionly.transcriberj.model.RequestBody;
import com.arc_e_tect.gradle.apionly.transcriberj.model.Response;
import com.arc_e_tect.gradle.apionly.transcriberj.model.Reusable;
import com.arc_e_tect.gradle.apionly.transcriberj.model.Schema;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.Emitter;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.EmitterContext;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.GeneratedClass;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.ManagedDependency;
import com.arc_e_tect.gradle.apionly.transcriberj.spi.Origin;

import java.io.IOException;
import java.io.InputStream;
import java.io.UncheckedIOException;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.EnumSet;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * The built-in emitter: the dependency-free classes every dialect builds on.
 *
 * <p>Each class carries its provenance, its constraints as constants, and, when its
 * schema describes an object, {@code body(...)} to write a conforming JSON body and
 * {@code fields(...)} to describe one.
 */
final class CoreEmitter implements Emitter {

    static final String ID = "core";

    private static final String INDENT = "    ";

    private final Shapes shapes;
    private final CoreClassNames names;
    private final String contractSha256;

    CoreEmitter(Shapes shapes, CoreClassNames names, String contractSha256) {
        this.shapes = shapes;
        this.names = names;
        this.contractSha256 = contractSha256;
    }

    @Override
    public String id() {
        return ID;
    }

    @Override
    public List<ManagedDependency> dependencies() {
        return List.of();
    }

    @Override
    public Set<Construct> represents() {
        EnumSet<Construct> represented = EnumSet.allOf(Construct.class);
        represented.removeAll(EnumSet.of(Construct.MULTIPLE_TYPES, Construct.BOOLEAN_SCHEMA,
                Construct.ONE_OF_INLINE_BRANCHES, Construct.ANY_OF_INLINE_BRANCHES));
        return represented;
    }

    @Override
    public void emit(EmitterContext context) {
        String pkg = context.settings().basePackage();
        String header = header(context);
        context.writeJava(pkg, "ContractJson", template("ContractJson", header, pkg, Map.of()));
        context.writeJava(pkg, "ContractField", template("ContractField", header, pkg, Map.of(
                "placeholder", JavaText.literal(context.settings().descriptionPlaceholder()),
                "depth", String.valueOf(context.settings().recursionDepth()))));
        context.writeJava(pkg, "ContractManifest", manifest(context, header, pkg));
        for (GeneratedClass generated : names.all()) {
            String source = generated.origin() == Origin.OPERATION
                    ? operationClass(context, generated, header)
                    : new ClassWriter(context, generated, header).write();
            context.writeJava(pkg, generated.simpleName(), source);
        }
    }

    static String header(EmitterContext context) {
        return "// Generated by the API-Only TranscriberJ from contract " + context.settings().contract() + " "
                + context.model().version() + ".\n// Do not edit: this file is overwritten on every build.\n";
    }

    private static String template(String name, String header, String pkg, Map<String, String> values) {
        String text;
        try (InputStream in = CoreEmitter.class.getResourceAsStream(name + ".java.template")) {
            text = new String(in.readAllBytes(), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        text = text.replace("${header}\n", header).replace("${package}", pkg);
        for (Map.Entry<String, String> value : values.entrySet()) {
            text = text.replace("${" + value.getKey() + "}", value.getValue());
        }
        return text;
    }

    private String manifest(EmitterContext context, String header, String pkg) {
        StringBuilder out = new StringBuilder(header);
        out.append("package ").append(pkg).append(";\n\n");
        out.append("/**\n * Every class generated from contract ").append(JavaText.comment(context.settings().contract()))
                .append(", and what each was generated from.\n *\n")
                .append(" * <p>One test can assert that the whole tree corresponds to the contract the build\n")
                .append(" * locked, by comparing {@link #CONTRACT_VERSION} and {@link #CONTRACT_SHA256} with it.\n */\n");
        out.append("public final class ContractManifest {\n\n");
        constant(out, "The contract's name, as the project subscribes to it.", "String", "CONTRACT",
                JavaText.literal(context.settings().contract()));
        constant(out, "The contract's title.", "String", "CONTRACT_TITLE",
                context.model().title() == null ? "null" : JavaText.literal(context.model().title()));
        constant(out, "The contract's version.", "String", "CONTRACT_VERSION",
                JavaText.literal(context.model().version()));
        constant(out, "The SHA-256 of the contract document the classes were generated from.", "String",
                "CONTRACT_SHA256", JavaText.literal(contractSha256));
        out.append(INDENT).append("/**\n")
                .append(INDENT).append(" * One generated class.\n")
                .append(INDENT).append(" *\n")
                .append(INDENT).append(" * @param className    its simple name, in this package\n")
                .append(INDENT).append(" * @param fragmentPath the fragment it came from, or null for an inline schema\n")
                .append(INDENT).append(" * @param location     the JSON pointer, in the contract, of what it came from\n")
                .append(INDENT).append(" * @param sha256       the hash of what it came from, as bundled\n")
                .append(INDENT).append(" */\n")
                .append(INDENT).append("public record Entry(String className, String fragmentPath, String location, ")
                .append("String sha256) {\n").append(INDENT).append("}\n\n");
        out.append(INDENT).append("/** Every generated class, in contract order. */\n")
                .append(INDENT).append("public static final java.util.List<Entry> ENTRIES = java.util.List.of(");
        List<GeneratedClass> all = names.all();
        for (int i = 0; i < all.size(); i++) {
            GeneratedClass g = all.get(i);
            out.append(i == 0 ? "\n" : ",\n").append(INDENT).append(INDENT).append(INDENT)
                    .append("new Entry(").append(JavaText.literal(g.simpleName())).append(", ")
                    .append(g.provenance().fragmentPath() == null ? "null" : JavaText.literal(g.provenance().fragmentPath()))
                    .append(", ").append(JavaText.literal(location(g))).append(", ")
                    .append(JavaText.literal(g.provenance().sha256())).append(')');
        }
        out.append(");\n\n");
        out.append(INDENT).append("private ContractManifest() {\n").append(INDENT).append("}\n}\n");
        return out.toString();
    }

    private static String location(GeneratedClass g) {
        return switch (g.origin()) {
            case SCHEMA -> "/components/schemas/" + Shapes.escape(g.key());
            case RESPONSE -> "/components/responses/" + Shapes.escape(g.key());
            case PARAMETER -> "/components/parameters/" + Shapes.escape(g.key());
            case REQUEST_BODY -> "/components/requestBodies/" + Shapes.escape(g.key());
            case INLINE_REQUEST, INLINE_RESPONSE, OPERATION -> g.key();
        };
    }

    /**
     * An operation's class: what a test needs to call it -- its method, its path and
     * a way to fill in its placeholders -- and, per response, its status and content type.
     */
    private String operationClass(EmitterContext context, GeneratedClass generated, String header) {
        Operation operation = context.model().operations().stream()
                .filter(o -> CoreClassNames.operationLocation(o).equals(generated.key()))
                .findFirst().orElseThrow();
        String name = generated.simpleName();
        StringBuilder out = new StringBuilder(header);
        out.append("package ").append(context.settings().basePackage()).append(";\n\n");
        out.append("/**\n * Generated from operation ").append(operation.method().name()).append(' ')
                .append(JavaText.comment(operation.path())).append(".\n */\n");
        out.append("public final class ").append(name).append(" {\n\n");
        Set<String> declared = new HashSet<>();
        java.util.function.BiConsumer<String[], String> constant = (typeAndName, value) -> {
            if (!declared.add(typeAndName[1])) {
                throw new GenerationException(name + " would declare " + typeAndName[1] + " twice; the responses of "
                        + generated.key() + " have status codes that read the same as constant names");
            }
            constant(out, typeAndName[2], typeAndName[0], typeAndName[1], value);
        };
        if (operation.operationId() != null) {
            constant.accept(new String[]{"String", "OPERATION_ID", "The operation's operationId."},
                    JavaText.literal(operation.operationId()));
        }
        constant.accept(new String[]{"String", "METHOD", "The operation's HTTP method."},
                JavaText.literal(operation.method().name()));
        constant.accept(new String[]{"String", "PATH", "The operation's path, as the contract writes it."},
                JavaText.literal(operation.path()));
        constant.accept(new String[]{"String", "LOCATION", "Where, in the contract, the operation is written."},
                JavaText.literal(generated.key()));
        constant.accept(new String[]{"String", "OPERATION_SHA256",
                "The SHA-256 of what this class was generated from, in RFC 8785 canonical JSON."},
                JavaText.literal(generated.provenance().sha256()));
        constant.accept(new String[]{"String", "CONTRACT_VERSION",
                "The version of the contract this class was generated from."},
                JavaText.literal(context.model().version()));

        RequestBody body = operation.requestBody();
        if (body != null && body.content() != null && !body.content().isEmpty()) {
            List<String> types = body.content().stream().map(MediaType::contentType).toList();
            if (types.size() == 1) {
                constant.accept(new String[]{"String", "REQUEST_CONTENT_TYPE", "The content type of the request body."},
                        JavaText.literal(types.get(0)));
            } else {
                constant.accept(new String[]{"java.util.List<String>", "REQUEST_CONTENT_TYPES",
                        "Every content type the request body may be sent as."}, listOf(types));
            }
        }
        if (operation.responses() != null) {
            for (Response response : operation.responses()) {
                // Appended to STATUS_ and CONTENT_TYPE_, so a leading digit is fine as it is.
                String code = response.status().toUpperCase(java.util.Locale.ROOT).replaceAll("[^A-Z0-9]", "_");
                if (response.status().matches("\\d{3}")) {
                    constant.accept(new String[]{"int", "STATUS_" + code,
                            "The status of the response the contract describes as " + response.status() + "."},
                            response.status());
                }
                List<String> types = response.content() == null ? List.of()
                        : response.content().stream().map(MediaType::contentType).toList();
                if (types.size() == 1) {
                    constant.accept(new String[]{"String", "CONTENT_TYPE_" + code,
                            "The content type of response " + response.status() + "."}, JavaText.literal(types.get(0)));
                } else if (types.size() > 1) {
                    constant.accept(new String[]{"java.util.List<String>", "CONTENT_TYPES_" + code,
                            "Every content type response " + response.status() + " may be sent as."}, listOf(types));
                }
            }
        }

        out.append(INDENT).append("private ").append(name).append("() {\n").append(INDENT).append("}\n\n");

        List<String> placeholders = new ArrayList<>();
        java.util.regex.Matcher matcher = java.util.regex.Pattern.compile("\\{([^}]+)}").matcher(operation.path());
        while (matcher.find()) {
            placeholders.add(matcher.group(1));
        }
        if (!placeholders.isEmpty()) {
            List<String> parameters = new ArrayList<>();
            Set<String> parameterNames = new HashSet<>();
            StringBuilder body2 = new StringBuilder();
            String expression = "PATH";
            for (String placeholder : placeholders) {
                String parameter = JavaText.variableName(placeholder);
                for (int i = 2; !parameterNames.add(parameter); i++) {
                    parameter = JavaText.variableName(placeholder) + i;
                }
                parameters.add("String " + parameter);
                body2.append(INDENT).append(INDENT).append("java.util.Objects.requireNonNull(").append(parameter)
                        .append(", ").append(JavaText.literal(parameter)).append(");\n");
                expression = expression + ".replace(" + JavaText.literal("{" + placeholder + "}") + ", "
                        + parameter + ")";
            }
            out.append(INDENT).append("/**\n")
                    .append(INDENT).append(" * The path with its placeholders filled in, in the order the path names them.\n")
                    .append(INDENT).append(" * The values are used as given, not encoded, so a pattern such as {@code .*}\n")
                    .append(INDENT).append(" * stays a pattern.\n")
                    .append(INDENT).append(" */\n");
            out.append(INDENT).append("public static String path(").append(String.join(", ", parameters))
                    .append(") {\n").append(body2)
                    .append(INDENT).append(INDENT).append("return ").append(expression).append(";\n")
                    .append(INDENT).append("}\n\n");
        }
        out.append("}\n");
        return out.toString();
    }

    private static String listOf(List<String> values) {
        return "java.util.List.of(" + String.join(", ", values.stream().map(JavaText::literal).toList()) + ")";
    }

    private static void constant(StringBuilder out, String doc, String type, String name, String value) {
        out.append(INDENT).append("/** ").append(JavaText.comment(doc)).append(" */\n")
                .append(INDENT).append("public static final ").append(type).append(' ').append(name)
                .append(" = ").append(value).append(";\n\n");
    }

    // ------------------------------------------------------------------ plan

    /** One parameter of {@code body(...)}. */
    private record Param(String property, String name, Shapes.ValueType type, boolean required) {
    }

    /** One constant member of every body. */
    private record Fixed(String property, String constant, String rendered) {
    }

    /** What {@code body(...)} takes and writes, in property order. */
    private record BodyPlan(List<Object> members, List<Param> required, List<Param> optional) {
    }

    /** Writes one core class. */
    private final class ClassWriter {

        private final EmitterContext context;
        private final GeneratedClass generated;
        private final String header;
        private final StringBuilder out = new StringBuilder();
        private final Set<String> members = new HashSet<>();
        private final String schemaLocation;
        private final List<String> privateConstants = new ArrayList<>();
        private final Map<String, String> constProperties = new java.util.HashMap<>();

        ClassWriter(EmitterContext context, GeneratedClass generated, String header) {
            this.context = context;
            this.generated = generated;
            this.header = header;
            this.schemaLocation = names.schemaLocation(generated);
        }

        String write() {
            String name = generated.simpleName();
            out.append(header).append("package ").append(context.settings().basePackage()).append(";\n\n");
            out.append("/**\n * ").append(JavaText.comment(origin())).append("\n */\n");
            out.append(generated.exposed() ? "public final class " : "final class ").append(name).append(" {\n\n");

            provenance();
            originConstants();
            Schema schema = generated.schema();
            Schema target = delegateTarget();
            BodyPlan plan = null;
            Shapes.Unrepresentable unrepresentable = null;
            if (generated.bodyShaped()) {
                try {
                    plan = plan(target != null ? target : schema, target != null
                            ? "/components/schemas/" + Shapes.escape(schema.ref()) : schemaLocation);
                } catch (Shapes.Unrepresentable e) {
                    unrepresentable = e;
                }
            }
            if (schema != null && target == null) {
                constraints(schema);
            }
            if (generated.bodyShaped() && target == null) {
                publicConstant("Whether a body may carry members the contract does not list.", "boolean", "OPEN",
                        String.valueOf(openness(schema)));
            }
            if (target == null) {
                // A delegating class writes no body of its own, so needs no constants for one.
                privateConstants.forEach(out::append);
            }

            out.append(INDENT).append("private ").append(name).append("() {\n").append(INDENT).append("}\n\n");
            method("The description of what this class was generated from.", "public static String description()",
                    List.of("return ContractField.PLACEHOLDER;"));

            if (generated.bodyShaped()) {
                if (target != null) {
                    delegate(target, plan, unrepresentable);
                } else {
                    body(plan, unrepresentable);
                    fields(schema);
                }
            }
            out.append("}\n");
            return out.toString();
        }

        private String origin() {
            String from = generated.provenance().fragmentPath() != null
                    ? generated.provenance().fragmentPath() : schemaLocation;
            return switch (generated.origin()) {
                case SCHEMA -> "Generated from schema " + from + ".";
                case RESPONSE -> "Generated from response " + from + ".";
                case PARAMETER -> "Generated from parameter " + from + ".";
                case REQUEST_BODY -> "Generated from request body " + from + ".";
                case INLINE_REQUEST -> "Generated from the request body schema at " + from + ".";
                case INLINE_RESPONSE -> "Generated from the response schema at " + from + ".";
                case OPERATION -> throw new IllegalStateException("an operation's class is not a schema's");
            };
        }

        /** The schema component a reusable response or request body only refers to. */
        private Schema delegateTarget() {
            Schema schema = generated.schema();
            if (schema == null || generated.origin() == Origin.SCHEMA || schema.ref() == null
                    || schema.types() != null || schema.properties() != null) {
                return null;
            }
            return shapes.component(schema.ref()).orElse(null);
        }

        private boolean openness(Schema schema) {
            try {
                return shapes.object(schema, schemaLocation).open();
            } catch (Shapes.Unrepresentable e) {
                return false;
            }
        }

        // -------------------------------------------------------- constants

        private void provenance() {
            if (generated.provenance().fragmentPath() != null) {
                publicConstant("The fragment this class was generated from.", "String", "FRAGMENT_PATH",
                        JavaText.literal(generated.provenance().fragmentPath()));
                publicConstant("The SHA-256 of that fragment as bundled, in RFC 8785 canonical JSON.", "String",
                        "FRAGMENT_SHA256", JavaText.literal(generated.provenance().sha256()));
            } else {
                publicConstant("Where, in the contract, the schema this class was generated from is written.",
                        "String", "LOCATION", JavaText.literal(schemaLocation));
                publicConstant("The SHA-256 of that schema, in RFC 8785 canonical JSON.", "String",
                        "SCHEMA_SHA256", JavaText.literal(generated.provenance().sha256()));
            }
            publicConstant("The version of the contract this class was generated from.", "String",
                    "CONTRACT_VERSION", JavaText.literal(context.model().version()));
        }

        private void originConstants() {
            ContractModel model = context.model();
            switch (generated.origin()) {
                case RESPONSE -> model.responses().stream().filter(r -> r.name().equals(generated.key()))
                        .findFirst().map(Reusable::value).ifPresent(r -> contentTypes(r.content()));
                case REQUEST_BODY -> model.requestBodies().stream().filter(b -> b.name().equals(generated.key()))
                        .findFirst().map(Reusable::value).ifPresent(b -> contentTypes(b.content()));
                case PARAMETER -> model.parameters().stream().filter(p -> p.name().equals(generated.key()))
                        .findFirst().map(Reusable::value).ifPresent(this::parameter);
                case INLINE_REQUEST, INLINE_RESPONSE -> inlineOperation(model);
                case SCHEMA -> {
                }
            }
        }

        private void contentTypes(List<MediaType> content) {
            List<String> types = content == null ? List.of() : content.stream().map(MediaType::contentType).toList();
            if (types.size() == 1) {
                publicConstant("The content type of the body.", "String", "CONTENT_TYPE",
                        JavaText.literal(types.get(0)));
            }
            publicConstant("Every content type the body may be sent as.", "java.util.List<String>",
                    "CONTENT_TYPES", "java.util.List.of(" + String.join(", ",
                            types.stream().map(JavaText::literal).toList()) + ")");
        }

        private void parameter(Parameter parameter) {
            if (parameter.name() != null) {
                publicConstant("The parameter's name.", "String", "NAME", JavaText.literal(parameter.name()));
            }
            if (parameter.in() != null) {
                publicConstant("Where the parameter is sent: path, query, header or cookie.", "String", "IN",
                        JavaText.literal(parameter.in()));
            }
            publicConstant("Whether the parameter must be sent.", "boolean", "REQUIRED",
                    String.valueOf(Boolean.TRUE.equals(parameter.required())));
            if (parameter.schema() != null && parameter.schema().ref() != null) {
                names.component(Origin.SCHEMA, parameter.schema().ref()).ifPresent(s ->
                        publicConstant("The class generated from the parameter's schema.", "Class<?>", "SCHEMA",
                                s.simpleName() + ".class"));
            }
        }

        private void inlineOperation(ContractModel model) {
            for (Operation operation : model.operations()) {
                String base = "/paths/" + Shapes.escape(operation.path()) + "/" + operation.method().key();
                if (!generated.key().startsWith(base + "/")) continue;
                if (operation.operationId() != null) {
                    publicConstant("The operation this class belongs to.", "String", "OPERATION_ID",
                            JavaText.literal(operation.operationId()));
                }
                publicConstant("The operation's method.", "String", "METHOD",
                        JavaText.literal(operation.method().name()));
                publicConstant("The operation's path.", "String", "PATH", JavaText.literal(operation.path()));
                if (generated.origin() == Origin.INLINE_RESPONSE && operation.responses() != null) {
                    for (Response response : operation.responses()) {
                        String at = base + "/responses/" + Shapes.escape(response.status()) + "/content/";
                        if (generated.key().startsWith(at)) {
                            publicConstant("The response's status.", "String", "STATUS",
                                    JavaText.literal(response.status()));
                            mediaType(response.content(), at);
                        }
                    }
                }
                RequestBody body = operation.requestBody();
                if (generated.origin() == Origin.INLINE_REQUEST && body != null) {
                    mediaType(body.content(), base + "/requestBody/content/");
                }
            }
        }

        private void mediaType(List<MediaType> content, String at) {
            for (MediaType m : content) {
                if (generated.key().equals(at + Shapes.escape(m.contentType()) + "/schema")) {
                    publicConstant("The content type of the body.", "String", "CONTENT_TYPE",
                            JavaText.literal(m.contentType()));
                }
            }
        }

        /** Constraint constants: the schema's own, or, for an object, those of each of its inline properties. */
        private void constraints(Schema schema) {
            if (generated.bodyShaped()) {
                List<Shapes.Property> properties;
                try {
                    properties = shapes.object(schema, schemaLocation).properties();
                } catch (Shapes.Unrepresentable e) {
                    return;
                }
                for (Shapes.Property p : properties) {
                    if (p.schema().ref() == null) {
                        constraintsOf(p.schema(), JavaText.constantName(p.name()) + "_", "property " + p.name());
                    }
                }
            } else if (schema.ref() == null) {
                constraintsOf(schema, "", "the value");
            }
        }

        private void constraintsOf(Schema s, String prefix, String of) {
            Constraints c = s.constraints();
            number(prefix + "MIN_LENGTH", "The minimum length of " + of + ".", c.minLength(), true);
            number(prefix + "MAX_LENGTH", "The maximum length of " + of + ".", c.maxLength(), true);
            if (c.pattern() != null) {
                publicConstant("The pattern " + of + " must match.", "String", prefix + "PATTERN",
                        JavaText.literal(c.pattern()));
            }
            if (s.format() != null) {
                publicConstant("The format of " + of + ".", "String", prefix + "FORMAT", JavaText.literal(s.format()));
            }
            number(prefix + "MINIMUM", "The minimum of " + of + ".", c.minimum(), false);
            number(prefix + "MAXIMUM", "The maximum of " + of + ".", c.maximum(), false);
            bound(prefix + "EXCLUSIVE_MINIMUM", "The exclusive minimum of " + of + ".", c.exclusiveMinimum());
            bound(prefix + "EXCLUSIVE_MAXIMUM", "The exclusive maximum of " + of + ".", c.exclusiveMaximum());
            number(prefix + "MULTIPLE_OF", "What " + of + " must be a multiple of.", c.multipleOf(), false);
            number(prefix + "MIN_ITEMS", "The minimum number of items in " + of + ".", c.minItems(), true);
            number(prefix + "MAX_ITEMS", "The maximum number of items in " + of + ".", c.maxItems(), true);
            if (c.uniqueItems() != null) {
                publicConstant("Whether the items of " + of + " must be unique.", "boolean", prefix + "UNIQUE_ITEMS",
                        c.uniqueItems().toString());
            }
            number(prefix + "MIN_PROPERTIES", "The minimum number of members of " + of + ".", c.minProperties(), true);
            number(prefix + "MAX_PROPERTIES", "The maximum number of members of " + of + ".", c.maxProperties(), true);
            if (s.enumValues() != null) {
                boolean strings = s.enumValues().stream().allMatch(v -> v instanceof String);
                String values = String.join(", ", s.enumValues().stream().map(this::javaValue).toList());
                publicConstant("The values " + of + " may take.",
                        strings ? "java.util.List<String>" : "java.util.List<Object>", prefix + "ENUM",
                        strings ? "java.util.List.of(" + values + ")"
                                : "java.util.Collections.unmodifiableList(java.util.Arrays.asList(" + values + "))");
            }
        }

        private void bound(String name, String doc, Object value) {
            if (value instanceof Boolean b) {
                publicConstant(doc, "boolean", name, b.toString());
            } else if (value instanceof Number n) {
                number(name, doc, n, false);
            }
        }

        private void number(String name, String doc, Number value, boolean count) {
            if (value == null) return;
            if (value instanceof Integer || (count && value instanceof Long l && l <= Integer.MAX_VALUE)) {
                publicConstant(doc, "int", name, String.valueOf(value.intValue()));
            } else if (value instanceof Long || value instanceof BigInteger) {
                publicConstant(doc, "long", name, value.longValue() + "L");
            } else {
                publicConstant(doc, "double", name, javaDouble(value.doubleValue()));
            }
        }

        private String javaValue(Object value) {
            if (value == null) return "null";
            if (value instanceof String s) return JavaText.literal(s);
            if (value instanceof Boolean || value instanceof Integer) return value.toString();
            if (value instanceof Long || value instanceof BigInteger) return ((Number) value).longValue() + "L";
            if (value instanceof Number n) return javaDouble(n.doubleValue());
            return JavaText.literal(CanonicalJson.write(value));
        }

        private static String javaDouble(double d) {
            return Double.isFinite(d) ? d + "d" : "Double.NaN";
        }

        private void publicConstant(String doc, String type, String name, String value) {
            member(name);
            constant(out, doc, type, name, value);
        }

        private void member(String name) {
            if (!members.add(name)) {
                throw new GenerationException(generated.simpleName() + " would declare " + name + " twice; "
                        + "rename one of the properties of " + schemaLocation + " so that their constants differ");
            }
        }

        // -------------------------------------------------------------- body

        private BodyPlan plan(Schema schema, String location) {
            Shapes.ObjectShape shape = shapes.object(schema, location);
            List<Object> planMembers = new ArrayList<>();
            List<Param> required = new ArrayList<>();
            List<Param> optional = new ArrayList<>();
            Set<String> parameterNames = new HashSet<>();
            for (Shapes.Property p : shape.properties()) {
                Const fixed = p.schema().constValue();
                if (fixed != null) {
                    planMembers.add(new Fixed(p.name(), JavaText.constantName(p.name()), fixedValue(p, fixed)));
                    continue;
                }
                String name = JavaText.variableName(p.name());
                for (int i = 2; !parameterNames.add(name); i++) {
                    name = JavaText.variableName(p.name()) + i;
                }
                Param param = new Param(p.name(), name, shapes.valueType(p.schema(), p.location()), p.required());
                planMembers.add(param);
                (p.required() ? required : optional).add(param);
            }
            return new BodyPlan(planMembers, required, optional);
        }

        /** The private constant a const property is written from, and how it is written. */
        private String fixedValue(Shapes.Property p, Const fixed) {
            Object value = fixed.value();
            String name = JavaText.constantName(p.name());
            String type;
            String literal;
            String rendered;
            if (value == null) {
                return "\"null\"";
            } else if (value instanceof String s) {
                type = "String";
                literal = JavaText.literal(s);
                rendered = "ContractJson.string(" + name + ")";
            } else if (value instanceof Integer i) {
                type = "int";
                literal = i.toString();
                rendered = "String.valueOf(" + name + ")";
            } else if (value instanceof Long l) {
                type = "long";
                literal = l + "L";
                rendered = "String.valueOf(" + name + ")";
            } else if (value instanceof Double d && Double.isFinite(d)) {
                type = "double";
                literal = javaDouble(d);
                rendered = "String.valueOf(" + name + ")";
            } else if (value instanceof Boolean b) {
                type = "boolean";
                literal = b.toString();
                rendered = "String.valueOf(" + name + ")";
            } else if (value instanceof BigInteger || value instanceof BigDecimal || value instanceof Number) {
                type = "String";
                literal = JavaText.literal(value.toString());
                rendered = name;
            } else {
                type = "String";
                literal = JavaText.literal(CanonicalJson.write(value));
                rendered = name;
            }
            // A property defined in several allOf branches is planned once, but a
            // class may be planned twice (for its body and a delegating response).
            String owner = constProperties.putIfAbsent(name, p.name());
            if (owner == null) {
                member(name);
                privateConstants.add(INDENT + "private static final " + type + " " + name + " = " + literal + ";\n\n");
            } else if (!owner.equals(p.name())) {
                member(name);
            }
            return rendered;
        }

        private String signature(List<Param> params, boolean optionalToo) {
            List<String> parts = new ArrayList<>();
            for (Param p : params) {
                parts.add(p.type().javaType(optionalToo && !p.required()) + " " + p.name());
            }
            return String.join(", ", parts);
        }

        private List<Param> all(BodyPlan plan) {
            List<Param> all = new ArrayList<>(plan.required());
            all.addAll(plan.optional());
            return all;
        }

        private void body(BodyPlan plan, Shapes.Unrepresentable unrepresentable) {
            String name = generated.simpleName();
            if (unrepresentable != null) {
                method("Cannot be generated from the contract; see the API-Only TranscriberJ report.",
                        "public static String body(Object... values)",
                        List.of(context.degraded(name, "body(...)", unrepresentable.finding)));
                return;
            }
            List<Param> all = all(plan);
            if (!plan.optional().isEmpty()) {
                List<String> args = new ArrayList<>(plan.required().stream().map(Param::name).toList());
                plan.optional().forEach(p -> args.add("null"));
                method("A body with every required member, and none of the optional ones.",
                        "public static String body(" + signature(plan.required(), false) + ")",
                        List.of("return body(" + String.join(", ", args) + ");"));
            }
            List<String> lines = new ArrayList<>();
            for (Param p : plan.required()) {
                if (p.type().list() || !Character.isLowerCase(p.type().javaType(false).charAt(0))) {
                    lines.add("java.util.Objects.requireNonNull(" + p.name() + ", " + JavaText.literal(p.name()) + ");");
                }
            }
            lines.add("StringBuilder json = new StringBuilder(\"{\");");
            for (Object m : plan.members()) {
                if (m instanceof Fixed f) {
                    lines.add("ContractJson.member(json, " + JavaText.literal(f.property()) + ", " + f.rendered() + ");");
                } else if (m instanceof Param p) {
                    String add = "ContractJson.member(json, " + JavaText.literal(p.property()) + ", "
                            + p.type().render(p.name()) + ");";
                    lines.add(p.required() ? add : "if (" + p.name() + " != null) " + add);
                }
            }
            lines.add("return ContractJson.close(json);");
            method(plan.optional().isEmpty() ? "A body; this contract has no optional members here."
                            : "A body with every required member, and each optional one that is not null.",
                    "public static String body(" + signature(all, true) + ")", lines);
        }

        private void delegate(Schema target, BodyPlan plan, Shapes.Unrepresentable unrepresentable) {
            String targetClass = names.component(Origin.SCHEMA, generated.schema().ref()).orElseThrow().simpleName();
            if (unrepresentable != null) {
                method("Cannot be generated from the contract; see the API-Only TranscriberJ report.",
                        "public static String body(Object... values)",
                        List.of("return " + targetClass + ".body(values);"));
            } else {
                if (!plan.optional().isEmpty()) {
                    method("A body with every required member; see {@link " + targetClass + "}.",
                            "public static String body(" + signature(plan.required(), false) + ")",
                            List.of("return " + targetClass + ".body(" + String.join(", ",
                                    plan.required().stream().map(Param::name).toList()) + ");"));
                }
                List<Param> all = all(plan);
                method("A body; see {@link " + targetClass + "}.",
                        "public static String body(" + signature(all, true) + ")",
                        List.of("return " + targetClass + ".body(" + String.join(", ",
                                all.stream().map(Param::name).toList()) + ");"));
            }
            method("The fields of a body; see {@link " + targetClass + "}.",
                    "public static java.util.List<ContractField> fields(String prefix)",
                    List.of("return " + targetClass + ".fields(prefix);"));
        }

        // ------------------------------------------------------------ fields

        private void fields(Schema schema) {
            String name = generated.simpleName();
            method("The fields of a body, each path starting with {@code prefix}.",
                    "public static java.util.List<ContractField> fields(String prefix)",
                    List.of("return fields(prefix, false, 0);"));
            List<String> lines = new ArrayList<>();
            lines.add("java.util.List<ContractField> fields = new java.util.ArrayList<>();");
            try {
                objectFields(shapes.object(schema, schemaLocation), "prefix", "optional", lines);
                lines.add("return fields;");
            } catch (Shapes.Unrepresentable e) {
                lines.clear();
                lines.add(context.degraded(name, "fields(String)", e.finding));
            }
            method("The fields of a body inside another: {@code optional} when the body that contains it is,\n"
                            + INDENT + " * and {@code depth} counting the recursive references followed to reach it.",
                    "static java.util.List<ContractField> fields(String prefix, boolean optional, int depth)", lines);
        }

        private void objectFields(Shapes.ObjectShape shape, String prefix, String optional, List<String> lines) {
            for (Shapes.Property p : shape.properties()) {
                String path = prefix + " + " + JavaText.literal(p.name());
                String opt = p.required() ? optional : "true";
                valueFields(p.schema(), p.location(), path, opt, lines);
            }
        }

        private void valueFields(Schema s, String location, String path, String opt, List<String> lines) {
            shapes.unrepresentable(s, location);
            String description = "ContractField.PLACEHOLDER";
            if (s.ref() != null && s.types() == null && s.properties() == null) {
                String targetClass = names.component(Origin.SCHEMA, s.ref()).orElseThrow().simpleName();
                Schema target = shapes.component(s.ref()).orElseThrow();
                description = targetClass + ".description()";
                if (shapes.isObject(target)) {
                    boolean open = shapes.object(target, "/components/schemas/" + Shapes.escape(s.ref())).open();
                    if (shapes.closesCycle(location)) {
                        lines.add("if (depth < ContractField.MAX_DEPTH) {");
                        lines.add(INDENT + field(path, "object", opt, description, false, open));
                        lines.add(INDENT + "fields.addAll(" + targetClass + ".fields(" + path + " + \".\", " + opt
                                + ", depth + 1));");
                        lines.add("} else {");
                        lines.add(INDENT + field(path, "object", opt, description, true, open));
                        lines.add("}");
                    } else {
                        lines.add(field(path, "object", opt, description, false, open));
                        lines.add("fields.addAll(" + targetClass + ".fields(" + path + " + \".\", " + opt
                                + ", depth));");
                    }
                    return;
                }
                if (shapes.isArray(target)) {
                    lines.add(field(path, "array", opt, description, false, false));
                    if (target.items() != null) {
                        itemFields(target.items(), "/components/schemas/" + Shapes.escape(s.ref()) + "/items", path,
                                opt, lines);
                    }
                    return;
                }
                lines.add(field(path, shapes.fieldType(target), opt, description, false, false));
                return;
            }
            if (shapes.isArray(s)) {
                lines.add(field(path, "array", opt, description, false, false));
                if (s.items() != null) itemFields(s.items(), location + "/items", path, opt, lines);
                return;
            }
            if (shapes.isObject(s)) {
                Shapes.ObjectShape shape = shapes.object(s, location);
                boolean map = shape.properties().isEmpty() && shape.open();
                lines.add(field(path, "object", opt, description, map, shape.open()));
                if (!map) objectFields(shape, path + " + \".\"", opt, lines);
                return;
            }
            lines.add(field(path, shapes.fieldType(s), opt, description, false, false));
        }

        private void itemFields(Schema items, String location, String path, String opt, List<String> lines) {
            shapes.unrepresentable(items, location);
            String itemPath = path + " + \"[]\"";
            if (items.ref() != null && items.types() == null && items.properties() == null) {
                Schema target = shapes.component(items.ref()).orElseThrow();
                if (!shapes.isObject(target)) return;
                String targetClass = names.component(Origin.SCHEMA, items.ref()).orElseThrow().simpleName();
                if (shapes.closesCycle(location)) {
                    lines.add("if (depth < ContractField.MAX_DEPTH) {");
                    lines.add(INDENT + "fields.addAll(" + targetClass + ".fields(" + itemPath + " + \".\", " + opt
                            + ", depth + 1));");
                    lines.add("} else {");
                    lines.add(INDENT + field(itemPath, "object", opt, targetClass + ".description()", true, false));
                    lines.add("}");
                } else {
                    lines.add("fields.addAll(" + targetClass + ".fields(" + itemPath + " + \".\", " + opt
                            + ", depth));");
                }
            } else if (shapes.isObject(items)) {
                objectFields(shapes.object(items, location), itemPath + " + \".\"", opt, lines);
            }
        }

        private String field(String path, String type, String optional, String description, boolean subsection,
                             boolean open) {
            return "fields.add(new ContractField(" + path + ", " + JavaText.literal(type) + ", " + optional + ", "
                    + description + ", " + subsection + ", " + open + "));";
        }

        // ------------------------------------------------------------ output

        private void method(String doc, String signature, List<String> lines) {
            out.append(INDENT).append("/**\n").append(INDENT).append(" * ").append(doc).append("\n")
                    .append(INDENT).append(" */\n");
            out.append(INDENT).append(signature).append(" {\n");
            for (String line : lines) {
                out.append(INDENT).append(INDENT).append(line).append('\n');
            }
            out.append(INDENT).append("}\n\n");
        }
    }
}
