"use strict";

const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const YAML = require("yaml");

const { load } = require("../src/config");
const { generateAsyncApi, isAggregate, AggregateError } = require("../src/aggregate");

function bundle(title, channelKey, operationKey) {
    return `asyncapi: 3.1.0
info:
  title: ${title}
  version: 1.0.0
servers:
  kafka:
    host: kafka:9092
    protocol: kafka
channels:
  ${channelKey}:
    address: ${channelKey}
operations:
  ${operationKey}:
    action: send
    channel:
      $ref: '#/channels/${channelKey}'
`;
}

function library(extraTargets = "", files = {}) {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "aop-aggregate-"));
    const config = `schemaVersion: 1
sources:
  root: specs
  asyncapi: asyncapi
defaults:
  asyncapi:
    outputName: asyncapi.yaml
build:
  staging: build/staging
targets:
  alpha:
    asyncapi:
      bundle: alpha.yaml
  beta:
    asyncapi:
      bundle: beta.yaml
  portfolio:
    asyncapi:
      aggregate:
        - alpha
        - beta
${extraTargets}`;
    const all = {
        "apionly.yaml": config,
        "specs/asyncapi/alpha.yaml": bundle("Alpha", "alphaEvents", "publishAlpha"),
        "specs/asyncapi/beta.yaml": bundle("Beta", "betaEvents", "publishBeta"),
        ...files,
    };
    for (const [rel, content] of Object.entries(all)) {
        const file = path.join(dir, rel);
        fs.mkdirSync(path.dirname(file), { recursive: true });
        fs.writeFileSync(file, content);
    }
    const loaded = load(path.join(dir, "apionly.yaml"));
    // Stage, as the pipeline does before generating.
    fs.cpSync(loaded.sourceRoot(), loaded.stagingRoot("asyncapi"), { recursive: true });
    return loaded;
}

test("recognises which targets are aggregates", () => {
    const config = library();
    assert.strictEqual(isAggregate(config, "portfolio", "asyncapi"), true);
    assert.strictEqual(isAggregate(config, "alpha", "asyncapi"), false);
});

test("merges every member's channels and operations into one document", () => {
    const config = library();

    const out = generateAsyncApi(config, "portfolio");
    const merged = YAML.parse(fs.readFileSync(out, "utf8"));

    assert.deepStrictEqual(Object.keys(merged.channels).sort(), ["alphaEvents", "betaEvents"]);
    assert.deepStrictEqual(Object.keys(merged.operations).sort(), ["publishAlpha", "publishBeta"]);
});

test("the aggregate carries its own identity, not a member's", () => {
    const config = library();

    const merged = YAML.parse(fs.readFileSync(generateAsyncApi(config, "portfolio"), "utf8"));

    assert.notStrictEqual(merged.info.title, "Alpha");
    assert.match(merged.info.title, /portfolio/);
    assert.match(merged.info.description, /alpha, beta/);
});

test("an explicit info block overrides the generated one", () => {
    const config = library();
    config.targets.portfolio.asyncapi.info = { title: "Everything", version: "9.9.9" };

    const merged = YAML.parse(fs.readFileSync(generateAsyncApi(config, "portfolio"), "utf8"));

    assert.strictEqual(merged.info.title, "Everything");
});

test("the generated file says plainly that it is generated", () => {
    // It lands in the staging tree, which is disposable -- but somebody will open
    // it while debugging a bundle, and should not try to edit it.
    const config = library();

    const text = fs.readFileSync(generateAsyncApi(config, "portfolio"), "utf8");

    assert.match(text, /GENERATED by api-only-publisher/);
    assert.match(text, /Do not edit/);
});

test("two members contributing the same key is an error, not a silent overwrite", () => {
    // Whichever member lost would simply vanish from the portfolio view, and
    // nothing would say so.
    const config = library("", { "specs/asyncapi/beta.yaml": bundle("Beta", "alphaEvents", "publishBeta") });

    assert.throws(() => generateAsyncApi(config, "portfolio"),
        (error) => error instanceof AggregateError
            && /redefines channels\.alphaEvents/.test(error.message)
            && /already contributed by 'alpha'/.test(error.message));
});

test("members may share a server, because publishing to one broker is normal", () => {
    // Both members declare the same kafka server. Rejecting that would make an
    // aggregate impossible for any landscape with a shared broker, which is most.
    const config = library();

    const merged = YAML.parse(fs.readFileSync(generateAsyncApi(config, "portfolio"), "utf8"));

    assert.deepStrictEqual(Object.keys(merged.servers), ["kafka"]);
});

test("but members disagreeing about a shared server is an error", () => {
    const config = library("", {
        "specs/asyncapi/beta.yaml": bundle("Beta", "betaEvents", "publishBeta")
            .replace("host: kafka:9092", "host: other-kafka:9092"),
    });

    assert.throws(() => generateAsyncApi(config, "portfolio"),
        (error) => error instanceof AggregateError
            && /disagrees about servers\.kafka/.test(error.message)
            && /may share a server, but not define it differently/.test(error.message));
});

test("an aggregate with no members is refused", () => {
    const config = library();
    config.targets.portfolio.asyncapi.aggregate = [];

    assert.throws(() => generateAsyncApi(config, "portfolio"),
        (error) => error instanceof AggregateError && /must list at least one target/.test(error.message));
});

test("a member that publishes no events is refused by name", () => {
    const config = library();
    config.targets.portfolio.asyncapi.aggregate = ["alpha", "ghost"];

    assert.throws(() => generateAsyncApi(config, "portfolio"),
        (error) => error instanceof AggregateError && /'ghost' declares no asyncapi bundle/.test(error.message));
});

test("a member whose bundle has not been staged is refused with its path", () => {
    const config = library();
    fs.rmSync(path.join(config.stagingDir("asyncapi"), "beta.yaml"));

    assert.throws(() => generateAsyncApi(config, "portfolio"),
        (error) => error instanceof AggregateError && /bundle root not found/.test(error.message));
});
