"use strict";

const test = require("node:test");
const assert = require("node:assert");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const YAML = require("yaml");

const { load } = require("../src/config");
const {
    generateOpenApi, openapiPushDown, isAggregate, mergeSection, pascalCase, AggregateError,
} = require("../src/aggregate");
const { prepare } = require("../src/pipeline");
const { forTargets } = require("../src/closure");
const { partition } = require("../src/split");

function member(title, pathKey, operationId, extra = "") {
    return `openapi: 3.1.1
info:
  title: ${title}
  version: 1.0.0
servers:
  production:
    url: https://api.example.test
security:
  - bearerAuth: []
tags:
  - name: ${title}
    description: ${title} operations.
paths:
  ${pathKey}:
    get:
      operationId: ${operationId}
      responses:
        '200':
          description: ok
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
${extra}`;
}

function library(extraTargets = "", files = {}, portfolio = "") {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "aop-aggregate-openapi-"));
    const config = `schemaVersion: 1
sources:
  root: specs
  openapi: openapi
defaults:
  openapi:
    outputName: openapi.yaml
build:
  staging: build/staging
${portfolio}
targets:
  alpha:
    openapi:
      bundle: alpha.yaml
  beta:
    openapi:
      bundle: beta.yaml
  portfolio:
    openapi:
      aggregate:
        - alpha
        - beta
${extraTargets}`;
    const all = {
        "apionly.yaml": config,
        "specs/openapi/alpha.yaml": member("Alpha", "/orders", "listOrders"),
        "specs/openapi/beta.yaml": member("Beta", "/payments", "listPayments"),
        ...files,
    };
    for (const [rel, content] of Object.entries(all)) {
        const file = path.join(dir, rel);
        fs.mkdirSync(path.dirname(file), { recursive: true });
        fs.writeFileSync(file, content);
    }
    const loaded = load(path.join(dir, "apionly.yaml"));
    fs.cpSync(loaded.sourceRoot(), loaded.stagingRoot("openapi"), { recursive: true });
    return loaded;
}

// ---- generateOpenApi (pass 1: what a member's bundle root shows unresolved) ----

test("recognises an OpenAPI aggregate the same way an AsyncAPI one is recognised", () => {
    const config = library();
    assert.strictEqual(isAggregate(config, "portfolio", "openapi"), true);
    assert.strictEqual(isAggregate(config, "alpha", "openapi"), false);
});

test("prefixes every member's paths with its target, by default", () => {
    const config = library();
    const { out } = generateOpenApi(config, "portfolio");
    const merged = YAML.parse(fs.readFileSync(out, "utf8"));
    assert.deepStrictEqual(Object.keys(merged.paths).sort(), ["/alpha/orders", "/beta/payments"]);
});

test("portfolio.openapi.paths: none leaves paths exactly as each member wrote them", () => {
    const config = library("", {}, "portfolio:\n  openapi:\n    paths: none\n");
    const { out } = generateOpenApi(config, "portfolio");
    const merged = YAML.parse(fs.readFileSync(out, "utf8"));
    assert.deepStrictEqual(Object.keys(merged.paths).sort(), ["/orders", "/payments"]);
});

test("the aggregate carries its own identity, not a member's, and an explicit info overrides it", () => {
    const config = library();
    const generated = YAML.parse(fs.readFileSync(generateOpenApi(config, "portfolio").out, "utf8"));
    assert.notStrictEqual(generated.info.title, "Alpha");
    assert.match(generated.info.title, /portfolio/);
    assert.match(generated.info.description, /alpha, beta/);

    config.targets.portfolio.openapi.info = { title: "Everything", version: "9.9.9" };
    const overridden = YAML.parse(fs.readFileSync(generateOpenApi(config, "portfolio").out, "utf8"));
    assert.strictEqual(overridden.info.title, "Everything");
});

test("the generated file says plainly that it is generated", () => {
    const text = fs.readFileSync(generateOpenApi(library(), "portfolio").out, "utf8");
    assert.match(text, /GENERATED by api-only-publisher/);
    assert.match(text, /Do not edit/);
});

test("servers merge silently when members agree, and fail when they do not", () => {
    const agreeing = library();
    const merged = YAML.parse(fs.readFileSync(generateOpenApi(agreeing, "portfolio").out, "utf8"));
    assert.deepStrictEqual(Object.keys(merged.servers), ["production"]);

    const disagreeing = library("", {
        "specs/openapi/beta.yaml": member("Beta", "/payments", "listPayments")
            .replace("url: https://api.example.test", "url: https://other.example.test"),
    });
    assert.throws(() => generateOpenApi(disagreeing, "portfolio"), (error) =>
        error instanceof AggregateError && /disagrees about servers\.production/.test(error.message));
});

test("components.securitySchemes merges silently when identical, and fails when members disagree, naming both", () => {
    const agreeing = library();
    const merged = YAML.parse(fs.readFileSync(generateOpenApi(agreeing, "portfolio").out, "utf8"));
    assert.deepStrictEqual(Object.keys(merged.components.securitySchemes), ["bearerAuth"]);

    const disagreeing = library("", {
        "specs/openapi/beta.yaml": member("Beta", "/payments", "listPayments")
            .replace("scheme: bearer", "scheme: basic"),
    });
    assert.throws(() => generateOpenApi(disagreeing, "portfolio"), (error) =>
        error instanceof AggregateError
            && /'beta' disagrees about components\.securitySchemes\.bearerAuth/.test(error.message)
            && /already contributed by 'alpha'/.test(error.message));
});

test("other components.* sub-maps merge too, agree mode, keyed by their own name", () => {
    const config = library("", {
        "specs/openapi/alpha.yaml": member("Alpha", "/orders", "listOrders",
            "  schemas:\n    Money:\n      type: object\n"),
        "specs/openapi/beta.yaml": member("Beta", "/payments", "listPayments",
            "  schemas:\n    Money:\n      type: object\n"),
    });
    const merged = YAML.parse(fs.readFileSync(generateOpenApi(config, "portfolio").out, "utf8"));
    assert.deepStrictEqual(merged.components.schemas.Money, { type: "object" });
});

test("tags are carried over as every member wrote them -- concatenated, not yet reconciled", () => {
    // Reconciliation needs each tag's name, which is not visible until the
    // aggregate's own output is bundled; see the openapiPushDown tests below.
    const config = library();
    const merged = YAML.parse(fs.readFileSync(generateOpenApi(config, "portfolio").out, "utf8"));
    assert.deepStrictEqual(merged.tags.map((t) => t.name), ["Alpha", "Beta"]);
});

test("two members contributing the same path is an error -- unreachable under target-prefix, reachable under none", () => {
    const collidingUnderNone = library("", {
        "specs/openapi/beta.yaml": member("Beta", "/orders", "listPayments"),
    }, "portfolio:\n  openapi:\n    paths: none\n");
    assert.throws(() => generateOpenApi(collidingUnderNone, "portfolio"), (error) =>
        error instanceof AggregateError && /'beta' redefines paths\.\/orders, already contributed by 'alpha'/.test(error.message));
});

test("an aggregate with no members is refused, by name", () => {
    const config = library();
    config.targets.portfolio.openapi.aggregate = [];
    assert.throws(() => generateOpenApi(config, "portfolio"),
        (error) => error instanceof AggregateError && /openapi\.aggregate must list at least one target/.test(error.message));
});

test("a member that declares no openapi bundle is refused by name", () => {
    const config = library();
    config.targets.portfolio.openapi.aggregate = ["alpha", "ghost"];
    assert.throws(() => generateOpenApi(config, "portfolio"),
        (error) => error instanceof AggregateError && /'ghost' declares no openapi bundle/.test(error.message));
});

test("a member that is itself an aggregate is refused -- nesting is not supported", () => {
    const config = library("  nested:\n    openapi:\n      aggregate:\n        - alpha\n");
    config.targets.portfolio.openapi.aggregate = ["alpha", "nested"];
    assert.throws(() => generateOpenApi(config, "portfolio"),
        (error) => error instanceof AggregateError && /'nested' is itself an aggregate; nesting is not supported/.test(error.message));
});

test("a member whose bundle has not been staged is refused with its path", () => {
    const config = library();
    fs.rmSync(path.join(config.stagingDir("openapi"), "beta.yaml"));
    assert.throws(() => generateOpenApi(config, "portfolio"),
        (error) => error instanceof AggregateError && /bundle root not found/.test(error.message));
});

// ---- openapiPushDown (pass 2: what only the bundled, resolved document shows) ----

function bundled({ security = ["- bearerAuth: []", "- basicAuth: []"], tags = [] } = {}) {
    return `openapi: 3.1.1
info:
  title: Portfolio
  version: 0.0.0
  description: Every API published across alpha, beta.
${tags.length ? `tags:\n${tags.map((t) => `  - name: ${t.name}\n    description: ${t.description}`).join("\n")}\n` : ""}paths:
  /alpha/orders:
    get:
      operationId: ListOrders
      responses:
        '200': { description: ok }
  /alpha/orders/{id}:
    delete:
      operationId: CancelOrder
      security: []
      responses:
        '200': { description: ok }
  /beta/payments:
    get:
      operationId: ListPayments
      responses:
        '200': { description: ok }
`;
}

const OWNERS = {
    "/alpha/orders": { member: "alpha", security: ["bearerAuth: []"] },
    "/alpha/orders/{id}": { member: "alpha", security: ["bearerAuth: []"] },
    "/beta/payments": { member: "beta", security: undefined },
};

test("prefixes every operation id with its path's member, in PascalCase", () => {
    const { text } = openapiPushDown(bundled(), OWNERS);
    const doc = YAML.parse(text);
    assert.strictEqual(doc.paths["/alpha/orders"].get.operationId, "AlphaListOrders");
    assert.strictEqual(doc.paths["/beta/payments"].get.operationId, "BetaListPayments");
});

test("pushes a member's root security onto an operation that does not already set its own", () => {
    const { text } = openapiPushDown(bundled(), OWNERS);
    const doc = YAML.parse(text);
    assert.deepStrictEqual(doc.paths["/alpha/orders"].get.security, ["bearerAuth: []"]);
});

test("leaves an operation's own security alone -- it replaces the root, it does not merge with it", () => {
    const { text } = openapiPushDown(bundled(), OWNERS);
    const doc = YAML.parse(text);
    assert.deepStrictEqual(doc.paths["/alpha/orders/{id}"].delete.security, []);
});

test("pushes nothing onto an operation whose member had no root security to begin with", () => {
    const { text } = openapiPushDown(bundled(), OWNERS);
    const doc = YAML.parse(text);
    assert.strictEqual(doc.paths["/beta/payments"].get.security, undefined);
});

test("adds the security note to info.description and x-security-note, only when something was pushed down", () => {
    const { text } = openapiPushDown(bundled(), OWNERS);
    const doc = YAML.parse(text);
    assert.match(doc.info.description, /moved onto the operations it contributes/);
    assert.match(doc["x-security-note"], /moved onto the operations it contributes/);

    const nothingPushed = openapiPushDown(bundled(), {
        "/alpha/orders": { member: "alpha", security: undefined },
        "/alpha/orders/{id}": { member: "alpha", security: undefined },
        "/beta/payments": { member: "beta", security: undefined },
    });
    const untouched = YAML.parse(nothingPushed.text);
    assert.doesNotMatch(untouched.info.description, /moved onto the operations/);
    assert.strictEqual(untouched["x-security-note"], undefined);
});

test("an unset operationIdStrategy other than target-prefix leaves operation ids untouched", () => {
    const { text } = openapiPushDown(bundled(), OWNERS, { operationIdStrategy: "none" });
    const doc = YAML.parse(text);
    assert.strictEqual(doc.paths["/alpha/orders"].get.operationId, "ListOrders");
});

test("two members' tags with the same name and an identical body merge into one", () => {
    const same = bundled({ tags: [{ name: "System", description: "Shared." }, { name: "System", description: "Shared." }] });
    const { text, reconciled } = openapiPushDown(same, OWNERS);
    const doc = YAML.parse(text);
    assert.deepStrictEqual(doc.tags, [{ name: "System", description: "Shared." }]);
    assert.deepStrictEqual(reconciled, []);
});

test("two members' tags with the same name and a different body are reconciled: reported, first wins", () => {
    const different = bundled({
        tags: [{ name: "Orders", description: "Alpha's words." }, { name: "Orders", description: "Beta's words." }],
    });
    const { text, reconciled } = openapiPushDown(different, OWNERS);
    const doc = YAML.parse(text);
    assert.deepStrictEqual(doc.tags, [{ name: "Orders", description: "Alpha's words." }]);
    assert.deepStrictEqual(reconciled, [{ section: "tags", key: "Orders" }]);
});

test("tags keep the order each name was first contributed in", () => {
    const many = bundled({
        tags: [{ name: "B", description: "b" }, { name: "A", description: "a" }, { name: "B", description: "b" }],
    });
    const { text } = openapiPushDown(many, OWNERS);
    assert.deepStrictEqual(YAML.parse(text).tags.map((t) => t.name), ["B", "A"]);
});

test("editing the document leaves everything it does not touch exactly as the bundler wrote it", () => {
    // A comment on an untouched value survives only if this is a document edit, not
    // a parse-and-restringify -- the same property version.js relies on.
    const withComment = bundled().replace("  /beta/payments:", "  # a comment nothing here touches\n  /beta/payments:");
    const { text } = openapiPushDown(withComment, OWNERS);
    assert.match(text, /# a comment nothing here touches/);
});

// ---- mergeSection reconcile mode, and pascalCase, directly ----

test("mergeSection reconcile mode merges an identical repeat silently and reports a differing one, first wins", () => {
    const into = {};
    const seen = {};
    mergeSection(into, { tags: { System: { description: "First." } } }, "tags", "alpha", seen, { mode: "reconcile" });
    const reconciled = mergeSection(into, { tags: { System: { description: "Second." } } }, "tags", "beta", seen, { mode: "reconcile" });
    assert.deepStrictEqual(into.tags.System, { description: "First." });
    assert.deepStrictEqual(reconciled, [{ section: "tags", key: "System", winner: "alpha", loser: "beta" }]);
});

test("pascalCase turns a kebab-case target into a PascalCase identifier prefix", () => {
    assert.strictEqual(pascalCase("user-account"), "UserAccount");
    assert.strictEqual(pascalCase("orders"), "Orders");
    assert.strictEqual(pascalCase("social_network"), "SocialNetwork");
});

// ---- other commands that read a target's bundle root must find an aggregate's ----

test("closure and split read an aggregate's generated root, not a bundle path it does not have", () => {
    // prepare() stages and generates before either of these ever reads a bundle
    // root; both used to call config.bundlePath() directly, which throws for an
    // aggregate -- it has no `bundle`, only `aggregate` -- rather than finding the
    // generated one.
    const config = library();
    prepare(config, { kinds: ["openapi"] });

    const closures = forTargets(config, ["openapi"]);
    const portfolioClosure = closures.get("portfolio");
    assert.ok(portfolioClosure, "the aggregate's own closure must be computable");
    assert.ok(portfolioClosure.files.some((f) => f.endsWith("portfolio_openapi_structure.yaml")),
        "the closure walk must start from the aggregate's generated root");

    const parts = partition(config, "target");
    assert.ok(parts.has("portfolio"), "split must be able to partition the aggregate too");
});
